project:
  fields: 
  - name: project_number
    type: string
    factory: |
      { TODO }

non_building:
  fields:
  - name: description
    type: text
    factory: |
      { TODO }
  relation:
    parent: project
    type: embeds_one

building:
  fields:
  - name: description
    type: text
    factory: |
      { TODO }
  - name: attribution
    type: string
    factory: |
      { TODO }
  - name: BCA_classification
    type: string
    factory: |
      { TODO }
  - name: project_catagories
    type: array
    factory: |
      { TODO }
   - name: project_sub-catagories
    type: array
    factory: |
      { TODO }
  relation:
    parent: project
    type: embeds_one

location:
  fields:[]
  relation:
    parent: building
    type: embeds_one

geoJSON:
  fields:[]
  relation:
    parent: location
    type: embeds_one

point_loc:
  fields:
  - name: lat
    type: double
    factory: |
      { TODO }
  - name: lon
    type: double
    factory: |
      { TODO }
  relation:
    parent: geoJSON
    type: embeds_one

boundary:
  fields:
  - name: boundary_points
    type: array
    factory: |
      { TODO }
  relation:
    parent: geoJSON
    type: embeds_one

address:
  fields:
  - name: name
    type: string
    factory: |
      { TODO }
  - name: street_number
    type: string
    factory: |
      { TODO }
  - name: street
    type: string
    factory: |
      { TODO }
  - name: suburb_area
    type: string
    factory: |
      { TODO }
  - name: state_county
    type: string
    factory: |
      { TODO }
  - name: country
    type: string
    factory: |
      { TODO }
  - name: postcode
    type: string
    factory: |
      { TODO }
  relation:
    parent: location
    type: embeds_one

project_source:
  fields:
  - name: competition_win
    type: boolean
    factory: |
      { TODO }
  - name: competition_URL
    type: string
    factory: |
      { TODO }
  relation:
    parent: building
    type: embeds_one

referred_by:
  fields:
  - name: BVN_staff_login
    type: string
    factory: |
      { TODO }
  - name: contact_name
    type: string
    factory: |
      { TODO }
  - name: contact_organisation
    type: string
    factory: |
      { TODO }
  relation:
    parent: project_source
    type: embeds_one

dims:
  fields:[]
  relation:
    parent: building
    type: embeds_one

height:
  fields:
  - name:measurement
    type:double
    factory: |
      { TODO }
  - name:standard_name
    type:double
    factory: |
      { TODO }
  - name:standard_version
    type:double
    factory: |
      { TODO }
  relation:
    parent: dims
    type: embeds_one

footprint_area:
  fields:
  - name:measurement
    type:double
    factory: |
      { TODO }
  - name:standard_name
    type:double
    factory: |
      { TODO }
  - name:standard_version
    type:double
    factory: |
      { TODO }
  relation:
    parent: dims
    type: embeds_one

GBA:
  fields:
  - name:measurement
    type:double
    factory: |
      { TODO }
  - name:standard_name
    type:double
    factory: |
      { TODO }
  - name:standard_version
    type:double
    factory: |
      { TODO }
  relation:
    parent: dims
    type: embeds_one

GFA:
  fields:
  - name:measurement
    type:double
    factory: |
      { TODO }
  - name:standard_name
    type:double
    factory: |
      { TODO }
  - name:standard_version
    type:double
    factory: |
      { TODO }
  relation:
    parent: dims
    type: embeds_one

NLA:
  fields:
  - name:measurement
    type:double
    factory: |
      { TODO }
  - name:standard_name
    type:double
    factory: |
      { TODO }
  - name:standard_version
    type:double
    factory: |
      { TODO }
  relation:
    parent: dims
    type: embeds_one


client:

relationships:

phase:

legacy:

media:

QA:
